name 'ericsson-named'
version '0.0.1'
source 'https://github.com/kividiot/puppet-module-named.git'
author 'erisson'
license 'Apache License, Version 2.0'
summary 'Manage named service'
description 'Manage named service'
project_page 'https://github.com/kividiot/puppet-module-named'

dependency 'puppetlabs/stdlib',   '>= 3.2.0'
