name 'named'
version 'v0.3.0'
source 'https://github.com/kividiot/puppet-module-named.git'
author 'erisson'
license 'Apache License, Version 2.0'
summary 'Manage named service'
description 'Manage named service'
project_page 'https://github.com/kividiot/puppet-module-named'

dependency 'puppetlabs/stdlib',   '>= 4.6.0'
